### ISSUE TITLE
Create a wishlist

### ISSUE THREAD

**Issue by Litou-lyh** [CSCI-GA-2820-SU24-001/wishlists#1]
As a wishlist manager / customer
I need to create a wishlist with a name
So that the customer can add some products into the wishlist.

## Details and Assumptions
- The request contains the name of the wishlist and the customer id associated with the wishlist to be created
- Each customer can have multiple wishlists.
- Each wishlist should have unique name.
- Customers can add some descriptions to the wishlist.
- A wishlist will be empty when created.

## Acceptance Criteria
Given database and service are running
When a wishlist is created
Then the wishlist should be added to the database, and customoers can perform CRUD operations for products inside the wishlist.

**Comment by tzuanwang** [comment]
Shall we have the unique id for the wishlist associated with customer id?
