### ISSUE TITLE
Update the Wishlist

### ISSUE THREAD

**Issue by tzuanwang** [CSCI-GA-2820-SU24-001/wishlists#13]
**As a** customer
**I need** to change the attributes of the wishlist  
**So that** I can modify the attribute of the wishlist if needed
   
 ### Details and Assumptions
 * The request contains the id associated with the wishlist and the attribute need to be modified
 * Wishlist with the given id exists
 * Each customer can have multiple wishlists
   
 ### Acceptance Criteria  
   
 Given a customer with an existing wishlist
 When a customer request to modify the attribute of a wishlist
 Then the attribute of the wishlist should be updated in the database

**Comment by Litou-lyh** [comment]
All tests passed when id issue fixed. Closed
