### ISSUE TITLE
Add CreateDate and ModifiedDate attribute to Wishlist

### ISSUE THREAD

**Issue by Litou-lyh** [CSCI-GA-2820-SU24-001/wishlists#42]
**As a** developer
**I want** to keep track of the Create Date and Modify Date for the wishlists
**So that** I can roll back to the previous state if errors happened
   
 ### Details and Assumptions
 * Original data model for Wishlists exists
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a specific wishlist exists
 When the developer uses GET to read a specific wishlist
 Then he will see these two attributes from the returned JSON data
```

**Comment by tzuanwang** [comment]
**As a** developer
**I want** to keep track of the Create Date and Modify Date for the wishlists
**So that** I can roll back to the previous state if errors happened
   
 ### Details and Assumptions
 * Original data model for Wishlists exists
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a specific wishlist exists
 When the developer uses GET to read a specific wishlist
 Then he will see these two attributes from the returned JSON data
```
