### ISSUE TITLE
CREATE web user interface for Wishlist microservice

### ISSUE THREAD

**Issue by sixtyferret** [CSCI-GA-2820-SU24-001/wishlists#80]
**As a** customer
**I need** a UI to create new wishlists
**So that** I can add new wishlists to the system
   
 ### Details and Assumptions
 * Making an API request to POST /wishlists creates a wishlist in the database
 * The UI will include a form for creating new wishlists
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a customer
When I access the homepage
Then I should see a form for entering wishlist details
And entering the details and submitting the form by clicking the create button should create a new wishlist
And if the wishlist is successfully created in the databse
Then a success message should be displayed on the UI
But if there is an error
Then a relevant error message should be displayed on the UI
```

**Comment by tzuanwang** [comment]
**As a** eCommerce Manager
**I need** a UI to create new wishlists
**So that** I can add new wishlists to the system
   
 ### Details and Assumptions
 * Making an API request to POST /wishlists creates a wishlist in the database
 * The UI will include a form for creating new wishlists
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a eCommerce manager
When I access the homepage
Then I should see a form for entering wishlist details
And entering the details and submitting the form by clicking the create button should create a new wishlist
And if the wishlist is successfully created in the databse
Then a success message should be displayed on the UI
But if there is an error
Then a relevant error message should be displayed on the UI
```
