### ISSUE TITLE
Create Database Models for Wishlist Service

### ISSUE THREAD

**Issue by sixtyferret** [CSCI-GA-2820-SU24-001/wishlists#9]
**As a** developer
**I need** to create a database for the wishlist service
**So that** wishlist data can be stored and managed efficiently

## Details and Assumptions
- SQLAlchemy will be used to set up the database models.
- Three main tables will be created: customers, wishlists, and wishlist_items.
- The customers table will have the following fields:
customer_id: Primary key, UUID
name: Text, name of the customer
- The wishlists table will have the following fields:
  - wishlist_id: Primary key, UUID
  - customer_id: Foreign key, references the customer
  - Name: String , name of the wishlist
- The wishlist_items table will have the following fields:
  - item_id: Primary key, UUID
  - wishlist_id: Foreign key, references the wishlist
  - product_id: UUID, id of the product
  - description:String, description of the product
  - price: Numeric, price of the product at the time of adding to the wishlist
- The wishlists table has a one-to-many relationship with the wishlist_items table.
- The customers table has a one-to-many relationship with the wishlists table.

## Acceptance Criteria
**Given** a developer setting up the database models
**When** the models are created using SQLAlchemy
**Then** the database should include the tables for customers, wishlists, and wishlist_items
**And** the relationships between the tables should be correctly established
**And** the database should be able to efficiently store and manage wishlist data

**Comment by Litou-lyh** [comment]
Can you link the pull request of this issue?
